### ISSUE TITLE
Widget height not update automatically

### ISSUE THREAD

**Issue by tsujido3r** [leon-vd/freeboard-table#3]
I did the modifications to the WidgeModel however the widget height is not automatically getting updated based on the table content. Any idea what might solve this issue?

**Comment by leon-vd** [comment]
I haven't looked at this in a long time. There is a good chance that Freeboard has changed since.

**Comment by tsujido3r** [comment]
Thanks @daleroy1. I managed with few other work arounds.

**Comment by mridah** [comment]
@tsujido3r can you please tell us how you got it to work ?
